const mongoose = require('mongoose');
const Restaurant = require('../models/restaurant')

mongoose.connect('mongodb://localhost/hackathon')

// Restaurant.collection.drop();

const seedRestaurants = () => {
	const Restaurants = [
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	{	name: String,
	address: String,
	pricePoint: Number,
	reservation: Boolean,
	smallThumb: String,
	backgrounds: [String],
	website: String,
	category: Number,
	likes: Number,
	hours: String,
	phoneNumber: String,
	attire: String,
	parking: String,
	paymentMethod: String,
	city: 'Seattle'
	},
	];
	Restaurants.forEach((restaurant) => {
		Restaurant.create(restaurant);
	});
	console.log('database seeded')
}

seedRestaurants()

setTimeout(function () {
	mongoose.connection.close();
}), 5000)