const mongoose = require('mongoose');
const Restaurant = require('../models/restaurant')

mongoose.connect('mongodb://localhost/hackathon')

// Restaurant.collection.drop();

const seedRestaurants = () => {
	const Restaurants = [
	{	name: "Shorty's",
	address: "2222 2nd Ave. Seattle, WA 98121",
	pricePoint: 1,
	reservation: false,
	smallThumb: 'https://s3-media4.fl.yelpcdn.com/bphoto/QBzOqD0ndfq7-_27ipAeTg/o.jpg',
	backgrounds: ['https://s3-media3.fl.yelpcdn.com/bphoto/OB5PoL6aOY6HJHis0YH3jA/o.jpg'],
	website: "shortydog.com",
	category: 3,
	likes: 0,
	hours: ["string"],
	phoneNumber: "string",
	attire: "Causal",
	parking: "Street",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "Add-a-Ball",
	address: "315 N 36th St. Unit 2B Seattle, WA 98103",
	pricePoint: 1,
	reservation: false,
	smallThumb: "https://s3-media4.fl.yelpcdn.com/bphoto/NyoKecoc08Et1x7XKNQEdA/o.jpg",
	backgrounds: ["string"],
	website: "N/A",
	category: 3,
	likes: 0,
	hours: ['string'],
	phoneNumber: "N/A",
	attire: "Casual",
	parking: "Street",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "Outer Planet Craft Brewing",
	address: "1812 12th Ave. Ste. 100 Seattle, WA 98122",
	pricePoint: 1,
	reservation: true,
	smallThumb: "https://s3-media4.fl.yelpcdn.com/bphoto/4IPKVFmSsO-ulaRJpi3tbA/o.jpg",
	backgrounds: ["string"],
	website: "outerplanetbrewing.com",
	category: 3,
	likes: 0,
	hours: ["string"],
	phoneNumber: "2067637000",
	attire: "Casual",
	parking: "Street",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "The Pink Door",
	address: "1919 Post Alley Seattle, WA 98101",
	pricePoint: 2,
	reservation: true,
	smallThumb: "https://s3-media3.fl.yelpcdn.com/bphoto/c_vzRF4h3ywnyeM116QFuA/o.jpg",
	backgrounds: ["https://s3-media3.fl.yelpcdn.com/bphoto/ILI5ZvXxKKyWMcet9ddbiA/o.jpg"],
	website: "thepinkdoor.net",
	category: 3,
	likes: 0,
	hours: ["string"],
	phoneNumber: "2064423221",
	attire: "Casual",
	parking: "Garage, Street",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "List",
	address: "2226 1st Ave. Seattle, WA 98121",
	pricePoint: 2,
	reservation: false,
	smallThumb: "https://s3-media3.fl.yelpcdn.com/bphoto/N8k9Ci2BFARygT-03uxXZA/o.jpg",
	backgrounds: ["https://s3-media1.fl.yelpcdn.com/bphoto/uxoKwXkExh46601e9McG0A/o.jpg"],
	website: "listbelltown.com",
	category: 3,
	likes: 0,
	hours: "String",
	phoneNumber: "(206) 441-1000",
	attire: "Casual",
	parking: "Street",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "Black Bottle",
	address: "String",
	pricePoint: 2,
	reservation: true,
	smallThumb: "https://s3-media3.fl.yelpcdn.com/bphoto/H9zEzoSse6ieIGIUw6Xr-Q/o.jpg",
	backgrounds: [String],
	website: "blackbottleseattle.com",
	category: 3,
	likes: 0,
	hours: ['String'],
	phoneNumber: 'String',
	attire: 'String',
	parking: 'String',
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "Purple Cafe and Wine Bar",
	address: "String",
	pricePoint: 3,
	reservation: true,
	smallThumb: "https://s3-media4.fl.yelpcdn.com/bphoto/YSZBoE6taHZfNhKepixaBw/o.jpg",
	backgrounds: [String],
	website: "purplecafe.com",
	category: 3,
	likes: 0,
	hours: ["string"],
	phoneNumber: "String",
	attire: "String",
	parking: "String",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "Dahlia Lounge",
	address: "2001 4th Ave. Seattle, WA 98121",
	pricePoint: 3,
	reservation: true,
	smallThumb: "https://s3-media1.fl.yelpcdn.com/bphoto/Q3N82kJiYo3W4gEE88TStQ/o.jpg",
	backgrounds: ["String"],
	website: "dahlialounge.com",
	category: 3,
	likes: 0,
	hours: ["String"],
	phoneNumber: "String",
	attire: "String",
	parking: "String",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	{	name: "RN74",
	address: "1433 4th Ave. Seattle, WA 98101",
	pricePoint: 3,
	reservation: true,
	smallThumb: "https://s3-media3.fl.yelpcdn.com/bphoto/O7AA3gviPRLTfunoLZM-9w/o.jpg",
	backgrounds: ["String"],
	website: "michaelmina.net",
	category: 3,
	likes: 0,
	hours: ["String"],
	phoneNumber: "String",
	attire: "String",
	parking: "String",
	acceptCreditCard: true,
	city: 'Seattle'
	},
	];
	Restaurants.forEach((restaurant) => {
		Restaurant.create(restaurant);
	});
	console.log('database seeded')
}

seedRestaurants()

setTimeout(function () {
	mongoose.connection.close();
}, 5000)